pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from your Git repository
                checkout scm
            }
        }
        stage('Build') {
            steps {
                // Navigate to the project directory
                dir('demo project\Jenkins_Demo') {
                    // Build the Maven project
                    sh 'mvn clean install'
                }
            }
        }
        stage('Run Tests') {
            steps {
                // Navigate to the project directory
                dir('demo project\Jenkins_Demo') {
                    // Run your Maven project's tests
                    sh 'mvn test'
                }
            }
        }
			stage('Run Project') {
			    steps {
			        // Navigate to the project directory
			        dir('Jenkins_Demo') {
			            // Run your Maven project with the full path to Maven executable
			            sh 'C:\\path\\to\\maven\\bin\\mvn exec:java' // Replace with the actual path
			        }
			    }
			}

    }
}

